FROM golang:1.24

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY ./../go.mod ./../go.sum ./
RUN go mod download

COPY . .

RUN go build -o /app/finet-server ./FileSearchServer.go

EXPOSE 8080

CMD ["/app/finet-server"]

